[2024-09-20T12:42:15.537+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: weekly_aggregate.spark_weekly_aggregate manual__2024-09-20T12:42:14.176289+00:00 [queued]>
[2024-09-20T12:42:15.560+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: weekly_aggregate.spark_weekly_aggregate manual__2024-09-20T12:42:14.176289+00:00 [queued]>
[2024-09-20T12:42:15.560+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-09-20T12:42:15.561+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-09-20T12:42:15.562+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-09-20T12:42:15.586+0000] {taskinstance.py:1300} INFO - Executing <Task(SparkSubmitOperator): spark_weekly_aggregate> on 2024-09-20 12:42:14.176289+00:00
[2024-09-20T12:42:15.592+0000] {standard_task_runner.py:55} INFO - Started process 358 to run task
[2024-09-20T12:42:15.604+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weekly_aggregate', 'spark_weekly_aggregate', 'manual__2024-09-20T12:42:14.176289+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/weekly_aggregate_dag.py', '--cfg-path', '/tmp/tmppfx4z3b6']
[2024-09-20T12:42:15.609+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask spark_weekly_aggregate
[2024-09-20T12:42:15.648+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-20T12:42:15.760+0000] {task_command.py:388} INFO - Running <TaskInstance: weekly_aggregate.spark_weekly_aggregate manual__2024-09-20T12:42:14.176289+00:00 [running]> on host ae946b97fe07
[2024-09-20T12:42:15.907+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weekly_aggregate
AIRFLOW_CTX_TASK_ID=spark_weekly_aggregate
AIRFLOW_CTX_EXECUTION_DATE=2024-09-20T12:42:14.176289+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-20T12:42:14.176289+00:00
[2024-09-20T12:42:15.934+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-09-20T12:42:15.955+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master yarn --name spark_weekly_aggregate --verbose --queue root.default /opt/***/dags/spark_aggregate.py 2024-09-20
[2024-09-20T12:42:16.133+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-09-20T12:42:16.135+0000] {spark_submit.py:490} INFO - JAVA_HOME is not set
[2024-09-20T12:42:16.155+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name spark_weekly_aggregate --verbose --queue root.default /opt/***/dags/spark_aggregate.py 2024-09-20. Error code is: 1.
[2024-09-20T12:42:16.161+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=weekly_aggregate, task_id=spark_weekly_aggregate, execution_date=20240920T124214, start_date=20240920T124215, end_date=20240920T124216
[2024-09-20T12:42:16.178+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task spark_weekly_aggregate (Cannot execute: spark-submit --master yarn --name spark_weekly_aggregate --verbose --queue root.default /opt/***/dags/spark_aggregate.py 2024-09-20. Error code is: 1.; 358)
[2024-09-20T12:42:16.189+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-09-20T12:42:16.214+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
